name: EcoPower
author: TheBusyBiscuit
description: 此插件為繁體翻譯版, 原作者"TheBusyBiscuit".
main: io.github.thebusybiscuit.ecopower.EcoPowerPlugin
website: https://github.com/TheBusyBiscuit/EcoPower

depend: [Slimefun]

version: ${project.version}
api-version: 1.14
