name: EcoPower
author: TheBusyBiscuit
description: 黏液科技附加 綠能發電 繁體翻譯版.
main: io.github.thebusybiscuit.ecopower.EcoPowerPlugin
website: https://github.com/TheBusyBiscuit/EcoPower

depend: [Slimefun]

version: ${project.version}
api-version: 1.14
